[package]
name = "brainfuck-interpreter"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["comment", "pointer_flow"]
comment = []
pointer_flow = []